### PR TITLE
The button is now enabled when the parameters change. Otherwise it is…

### PR DESCRIPTION
**Pull request by spiresheep**
… disabled.

### CODE REVIEW

**Comment by spiresheep** [comment]
> Upload a demo for it and I'll review it shortly.

Demo updated.

**Comment by kranar** [comment]
There are a series of buttons that are used to test/debug the page, what does the Enabled/Not Enabled button do?

**Comment by spiresheep** [comment]
> There are a series of buttons that are used to test/debug the page, what does the Enabled/Not Enabled button do?

It's some legacy code, I'll get rid of it.

**Comment by spiresheep** [comment]
Demo bas been updated.

**Pull request merged**
